### ISSUE TITLE
breaks when it loses connection

### ISSUE THREAD

**Issue by jelmer** [jelmer/prometheus-xmpp-alerts#1]
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/jelmer/prometheus_xmpp.py", line 72, in __call__
    id_ = self.client.send(nbxmpp.protocol.Message(self.to_jid, text, typ='chat'))
  File "/usr/lib/python3/dist-packages/nbxmpp/dispatcher_nb.py", line 576, in send
    self.sm.request_ack()
  File "/usr/lib/python3/dist-packages/nbxmpp/smacks.py", line 94, in request_ack
    self._owner.Connection.send(r, False)
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by jelmer** [comment]
I haven't actually been able to reproduce this in a while.

**Comment by jelmer** [comment]
This should be fixed with the move to slixmpp.
