### ISSUE TITLE
time data does not match format

### ISSUE THREAD

**Issue by jangrewe** [jelmer/prometheus-xmpp-alerts#12]
After running it for a couple of days and getting plenty of alerts successfully, the alerts suddenly stopped and `prometheus-xmpp-alerts` keels on throwing errors:
```
ERROR    Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/prometheus-xmpp-alerts", line 131, in serve_alert
    text = '\n'.join(create_message(alert))
  File "/prometheus_xmpp/__init__.py", line 34, in create_message
    parse_timestring(alert['startsAt']).isoformat(timespec='seconds'),
  File "/prometheus_xmpp/__init__.py", line 26, in parse_timestring
    return datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S.%fZ')
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-05-19T15:07:56.89489802Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
INFO     172.17.0.1 [20/May/2019:14:34:44 +0000] "POST /alert HTTP/1.1" 500 244 "-" "Alertmanager/0.17.0"
```

That seems a bit strange, because to me the timestamp does look like it's in the expected format?

**Comment by jangrewe** [comment]
It looks like Alertmanager is sending the notification with `RFC3339Nano` timestamps (9 digit accuracy), while RFC3339Micro (6 digit accuracy) is expected.

**Comment by jangrewe** [comment]
Ugh, it's only 8 digits, and you already have a workaround for nanoseconds! Maybe trailing zeros get trimmed, which may result in less digits... i'll test and send you a PR.

**Comment by jangrewe** [comment]
Fixed by #13

**Comment by azrdev** [comment]
Got the same issue here with `prometheus-alertmanager-0.10.0-1.git133c888.fc28.x86_64`, it seems my alertmanager started using `+` instead of `Z` as timezone delimiter:
~~~
ValueError: time data '2019-12-14T18:29:02.469242983+01:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'                                                                                 
INFO     ::1 [15/Dec/2019:13:45:06 +0000] "POST /alert/jid@example.com HTTP/1.1" 500 244 "-" "Alertmanager/"
~~~

**Comment by joudinet** [comment]
It seems my alertmanager may send time data without milliseconds:
`ValueError: time data '2023-03-30T17:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'`

**Comment by jelmer** [comment]
@joudinet What version of prometheus are you running?

**Comment by joudinet** [comment]
The one from debian stable: Version 2.24.1+ds-1+b7

**Comment by joudinet** [comment]
FYI, this bug is still present in the last Debian stable, using Grafana 9.5.3:
```
Jun 13 23:00:16 monitor prometheus-xmpp-alerts[371]: INFO     127.0.0.1 [13/Jun/2023:23:00:16 +0000] "POST /alert HTTP/1.1" 500 245 "-" "Grafana"
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]: ERROR    Error handling request
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]: Traceback (most recent call last):
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     resp = await request_handler(request)
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 504, in _handle
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     resp = await handler(request)
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:            ^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/local/bin/prometheus-xmpp-alerts", line 146, in serve_alert
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     text = '\n'.join(create_message_short(alert))
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3/dist-packages/prometheus_xmpp/__init__.py", line 38, in create_message_short
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     parse_timestring(alert['startsAt']).isoformat(timespec='seconds'),
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3/dist-packages/prometheus_xmpp/__init__.py", line 26, in parse_timestring
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     return datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S.%f%z')
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:   File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]:     raise ValueError("time data %r does not match format %r" %
Jun 14 07:00:19 monitor prometheus-xmpp-alerts[371]: ValueError: time data '2023-06-14T03:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

Do you have a better solution in mind than my workaround to call `datetime.strptime` without '.%f' in the format if the variable `ts` doesn't contain a '.' (dot) character:
```
def parse_timestring(ts):
    # strptime doesn't understand nanoseconds, so discard the last three digits
    ts = re.sub(r'\.([0-9]{6})([0-9]*)([^0-9])', r'.\1\3', ts)
    if "." in ts:
        return datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S.%f%z')
    else:
        return datetime.strptime(ts, '%Y-%m-%dT%H:%M:%S%z')
```
